### ISSUE TITLE
Digital Ocean: Host key verification failed.

### ISSUE THREAD

**Issue by adc17** [nix-community/linuxkit-nix#31]
I'm having ssh-related issues with a nixops deployment to digital ocean.

The initial ssh into the machine goes fine:
```
machine> waiting for SSH........................                                                                                                                
machine> running nixos-infectWarning: Permanently added '165.22.236.211' (ECDSA) to the list of known hosts.   
```

The installer seems to be running ok until we get to the reboot:
```
machine> waiting for the machine to finish rebooting....[down]..................................................................................................
[up]
```

Then, the address is added to known_hosts again?
```
Warning: Permanently added '165.22.236.211' (ED25519) to the list of known hosts.
```

Build info is output:
```
these derivations will be built:
  /nix/store/018fxn4x26vgq2iy56nvdbdg0pk7zik2-vconsole.conf.drv
  ....
```

And our third? ssh connection fails.
```
cannot build on 'ssh://root@165.22.236.211': cannot connect to 'root@165.22.236.211': Host key verification failed.
```

(Nixops then errors with `error: a 'x86_64-linux' with features {} is required to build '/nix/store/9j73g9irkbd904xs6m1kjhzjkcinziz6-append-initrd-secrets.drv', but I am a 'x86_64-darwin' with features {benchmark, big-parallel, nixos-test}`).

Any idea what could be causing this issue with the ssh connection? 

I've posted here instead of https://github.com/NixOS/nixops, as I suspect I need to somehow configure digital ocean and linuxkit to trust each others' keys, but I'm not clear on what exactly needs to be done.

One thing I did try was adding the `client.pub` key to digital ocean, but the result was exactly the same.

Let me know if you need more info for debugging.

**Comment by zimbatm** [comment]
`error: a 'x86_64-linux' with features {} is required to build...` means that nix doesn't know how to build the target arch, which happens if it doesn't have any remote builder with that capability.

First have a look in /etc/nix/nix.conf to see if linuxkit-nix has been installed in the builders. Next, try and connect to the linuxkit-nix builder with ssh.

**Comment by adc17** [comment]
I assume I'm getting `error: a 'x86_64-linux' with features {} is required to build...` because building remotely fails and the system falls back to building natively? Otherwise I don't know how I end up with `I am a 'x86_64-darwin`.

Anyway, no `/etc/nix/nix.conf` (I'm not using nix-darwin), but I have a machines file:
```
sudo cat /etc/nix/machines
> ssh://nix-linuxkit x86_64-linux /Users/adc/.cache/nix-linuxkit-builder/keys/client 1 1 kvm,big-parallel
```

and ssh seems to work:
```
ssh nix-linuxkit
> lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
> lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
> ~ # 
```

**Comment by zimbatm** [comment]
Yes that's what I think too.

Try running this on your macOS machine:
```sh
$ cat "$(nix-build --expr '(import <nixpkgs> { system = "x86_64-linux"; }).runCommand "hello" {} "echo hello > $out"')"
hello
```

**Comment by adc17** [comment]
Works great—builds the first time, then I get exactly that output:
```
$ cat "$(nix-build --expr '(import <nixpkgs> { system = "x86_64-linux"; }).runCommand "hello" {} "echo hello > $out"')"
hello
```

**Comment by zimbatm** [comment]
okay so linuxkit-nix is working fine. nixops uses the target host as a remote builder when the system is not the same as the client and that probably overrides the linuxkit-nix builder. I think the issue is really with nixops, the DO provider and why it's changing ssh keys on the host.

**Comment by adc17** [comment]
Thanks for your prompt replies @zimbatm, I'll close this once nixops have confirmed the problem is their side.

**Comment by adc17** [comment]
Do you have any advice on looking into this myself? I don't see a lot of replies to open issues in the nixops repo.

**Comment by zimbatm** [comment]
Most of the time with open source you have to learn how to do things yourself. People are busy with their own lives.

Here I would first read the python code in `nixops/backends/digital_ocean.py` in the nixops repo to better understand what it's doing. It says something about rebooting the machine two times, which might explain why is it not immediately available. I also see that it sends KnownHosts to /dev/null which explains why it re-discovers the host public key upon reconnection.

A few other things I would try:
* reduce the machine configuration to a minimum
* try and start the machine only, wait a bit and then deploy
* look in DO if they have any machine logs available

Good luck!

**Comment by adc17** [comment]
I've found a solution:

1. `export NIX_REMOTE_SYSTEMS=/etc/nix/machines`
2. `nixops deploy -d trivial --allow-reboot`

When I point `NIX_REMOTE_SYSTEMS` to the `machines` file autogenerated by linuxkit, nixops uses the linuxkit vm for the part of the build that was previously crashing.  `--allow-reboot` is necessary to prevent `Exception: the new configuration requires a reboot to take effect (hint: use ‘--allow-reboot’)` from being thrown. 

Deploying to DO now actually works pretty well on my mac!

**Comment by zimbatm** [comment]
maybe that's worth adding to the linuxkit-nix readme actually. Wanna submit a PR with a NixOps + LinuxKit section?

**Comment by adc17** [comment]
The solution feels slightly hacky to me, so I'm not sure how I feel about putting it into the readme? But if you disagree I'm happy to do that.

**Comment by zimbatm** [comment]
I added it to https://github.com/nix-community/linuxkit-nix/#error-x86_64-linux-is-require-to-build-
